name: pomodoro_app
description: AplicaciÃ³n Pomodoro minimalista con Flutter, GetX y SQLite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # Audio
  audioplayers: ^5.2.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Utils
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/icons/
